# Generated by Django 4.0.5 on 2022-07-16 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_price', models.PositiveIntegerField()),
                ('order', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripToken', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
